config/routes.rb
Rails.application.routes.draw do

  
  resources :courses do
  	resources :comments
  end

  resources :students

  resources :profesors do
  	resources :evaluations
  end
  
  devise_for :users
	  root "welcome#index"
  	get 'welcome/index'
  	resources :users
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :user
  has_many :evaluations
  after_create :default 

  private def default



  	Profesor.update(id, :ranking => 0)
  	Profesor.update(id, :ev => 0)
  end
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
    @user = User.find(params[:id])
    @courses = []

    for i in UserCourse.all
      if i.user_id == @user.id
        @courses << Course.find(i.course_id)
      end
    end
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:user_id)
    end
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/views/profesors/_form.html.erb
<%= form_with(model: profesor, local: true) do |form| %>
  <% if profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :ranking %>
    <%= form.number_field :ranking %>
  </div>

  <div class="field">
    <%= form.label :ev %>
    <%= form.number_field :ev %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

app/views/profesors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profesores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= User.find(profesor.user_id).name %></td>
        <td><%= User.find(profesor.user_id).email %></td>
        <td><%= link_to 'Ver', profesor %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profesors/new.html.erb
<h1>New Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Back', profesors_path %>

app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= User.find(@profesor[:user_id]).name %></h1>
<h4><%= User.find(@profesor[:user_id]).email %></h4>

<table>
  <thead>
    <tr>
      	<th>Curso</th>
      	<th>NRC</th>
     	 <th></th>


    </tr>
  	</thead>
  	<tbody>
		<% @courses.each do |course| %>
			<tr>
				<td> <%= course.name %></td>
				<td> <%= course.nrc %></td>
				<td><%= link_to 'Ver curso', course %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% evaluar = 0 %>
<% prof = 0 %>

<% if current_user.id == User.find(@profesor.user_id).id %>
	<% prof = 1 %>
<% end %>

<% for i in UserCourse.all %>
	<% nrc = 0 %>
	<%if i.user_id == User.find(@profesor.user_id).id%>
		<% id = i.course_id %>
	<% end %>
	<% for e in UserCourse.all %>

		<%if e.course_id == id && e.user_id == current_user[:id] && e.user_id != i.user_id %>
			<% evaluar = 1 %>
		<% end %>
	<% end %>

<% end %>

<% suma = 0%>
<% ctda = 0 %>
<% @profesor.evaluations.each do |e| %>
	    
	<% suma += e.mark %>
	<% ctda += 1 %>
  
<% end %>

<% promedio = 0 %>
<% if ctda > 0.0 %>
	<% promedio = suma/ctda %>
<% end %>
<h2>Evaluacion promedio: <%= promedio %> </h2> <br>

<% if prof == 1 %>
	<h2>Evaluaciones</h2>
	<% @profesor.evaluations.each do |e| %>
	    <h4><%= User.find(Student.find(e.student_id).user_id).name %></h4>

	    <h5>Evaluación: <%= e.mark %></h5>

		<p>
		   <%= e.description %>
		</p><br>

	  
	<% end %>
<% end %>



<% if evaluar == 1 %>
 
	<h2>Evaluar</h2>
	<%= form_with(model: [ @profesor, @profesor.evaluations.build ], local: true) do |form| %>
	  <p>
	  	<%= form.label :mark %><br>

		<%= form.select(:mark, [1,2,3,4,5,6,7], {}) %>


	  </p>
	  <p>
	    <%= form.label :description %><br>
	    <%= form.text_area :description %>
	  </p>
	  <p>
	    <%= form.submit %>
	  </p>
	<% end %>
<% end %>

  


<%= link_to 'Back', profesors_path %>